### ISSUE TITLE
cannot install optional dependencies

### ISSUE THREAD

**Issue by cgahr** [nix-community/pyproject.nix#151] opened 2024-09-11 07:33 UTC
I'm trying to automatically add some optional dependencies to my flake devShell following #65.
However I'm unable to make it work and have no clue why.

Do you have an idea what's going wrong?

nix repl correctly shows all optional dependencies under `project.dependencies.extras`.

`pyproject.toml`:
```toml
...
[project.optional-dependencies]
tests = [
    "coverage",
    "pytest",
    "pytest-cov",
    "pytest-mock"
]
...
```

`flake.nix`:
```nix
  outputs =
    {
      self,
      nixpkgs,
      pyproject-nix,
    }:
    let
      system = "x86_64-linux";
      pkgs = import nixpkgs { inherit system; };

      project = pyproject-nix.lib.project.loadPyproject { projectRoot = ./.; };
      python = pkgs.python312;
    in
    {
      devShells."${system}".default =
        let
          attrs = project.renderers.withPackages {
            inherit python;
            extras = [ "tests" ];
          };
          pythonEnv = python.withPackages attrs;
        in
        pkgs.mkShell {
          packages = [ pythonEnv ];
          shellHook = ''
            export PYTHONPATH="$(pwd)/src"
          '';
        };
    };
```

**Comment by adisbladis** [comment] 2024-09-11 22:09
This is because of a recent regression. Fixed in https://github.com/nix-community/pyproject.nix/commit/7fb2b7a09bf43efbcdfa16ceaa64fdff2fc8c50d.

**Closed** 2024-09-11 22:08 UTC

**Comment by cgahr** [comment] 2024-09-12 08:36
Works like a charm, thanks a lot!
